plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'evaluation'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	all {
		exclude group: 'commons-logging', module: 'commons-logging'
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'

	// langChain
	implementation 'dev.langchain4j:langchain4j:1.11.9'
	implementation 'dev.langchain4j:langchain4j-google-ai-gemini:1.11.9'
	// CSV
	implementation 'com.opencsv:opencsv:5.9'
}

tasks.named('test') {
	useJUnitPlatform {
		if (System.getProperty('tags') != null) {
			includeTags System.getProperty('tags')
		}
	}
}

tasks.named('bootJar') {
	archiveFileName = 'app.jar'
	archiveVersion.set('')
}